#!/bin/sh
#Runs your script on the cluster using spark2 and Python 3. 
#This requires to export the 2 environment variables below, and to add --conf spark.yarn.appMasterEnv.SPARK_HOME=/usr/hdp/current/spark2-client to your spark-submit
#For Python 3 we need to set HDP_VERSION, and PYSPARK_PYTHON
export SPARK_MAJOR_VERSION=2
export SPARK_HOME=/usr/hdp/current/spark2-client
export PYSPARK_PYTHON="/usr/bin/python3.5"
zip -r histogram.zip histogram/
spark-submit --master yarn --deploy-mode cluster \
--conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.enabled=true \
--conf spark.yarn.appMasterEnv.SPARK_HOME=/usr/hdp/current/spark2-client \
--py-files histogram.zip spark.py
