#!/bin/sh
#Runs your script on the cluster using spark2. 
#This requires to export the 2 environment variables below, and to add --conf spark.yarn.appMasterEnv.SPARK_HOME=/usr/hdp/current/spark2-client to your spark-submit
export SPARK_MAJOR_VERSION=2
export SPARK_HOME=/usr/hdp/current/spark2-client
zip -r histogram.zip histogram/ && \
spark-submit --master yarn-cluster --conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.enabled=true --conf spark.yarn.appMasterEnv.SPARK_HOME=/usr/hdp/current/spark2-client --files log4j.properties --py-files histogram.zip spark.py
